# Generated by Django 4.2.1 on 2023-06-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('profesion', models.CharField(max_length=50, verbose_name='Profesion')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('descripcion', models.TextField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.CharField(max_length=250, verbose_name='Ruta imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('categoria', models.ManyToManyField(blank=True, related_name='productos', to='productos.categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('nombre', models.CharField(default='Anonimo', max_length=100, verbose_name='Nombre')),
                ('mensaje', models.CharField(max_length=800, verbose_name='mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
