# Generated by Django 4.2.1 on 2023-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_descripcion_alter_product_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
    ]
