# Generated by Django 4.2.1 on 2023-06-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_product_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='password',
            field=models.CharField(default='default_password', max_length=128, verbose_name='Contrasena'),
        ),
    ]
